### ISSUE TITLE
Add GitHub action to create apk release

### ISSUE THREAD

**Issue by upkarlidder** [Pyrrha-Platform/Pyrrha-Mobile-App#24]
When:
- successful merge into master branch
- manually

The release should show up in the [`releases`](https://github.com/pyrrha-platform/Pyrrha-Mobile-App/releases) section of the repository.

Investigate here - https://github.com/marketplace?type=actions&query=android+

**Comment by krook** [comment]
This should be parameterized to allow for both Pyrrha and Prometeo builds, pulling from different properties files. The code itself can continue to have names such as `PyrrhaApplication` as this is upstream.

**Comment by krook** [comment]
Also a good tutorial here: https://www.freecodecamp.org/news/use-github-actions-to-automate-android-development/
